<a href="https://colab.research.google.com/github/sriramrangu/Machine-Learning-Practice/blob/main/SVD_and_Netfilx_Recommendation_Project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building a Recommendation System for netflix Using SVD algo

In [1]:
# Nessasary Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("/content/movies.csv") #The File is uploaded in from the Local Memory
data

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [ ]:
# Connecting the file from the G-Drive to G-Colab

In [4]:
from google.colab import drive

In [6]:
drive.mount("/content/drive")

Mounted at /content/drive

In [11]:
netflix_dataset = pd.read_csv("/content/drive/MyDrive/combinedNetflixData.txt", header=None, names=['CustId', 'Rating'], usecols=[0,1])

In [12]:
netflix_dataset

           CustId  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [15]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24058263 entries, 0 to 24058262
Data columns (total 2 columns):
 #   Column  Dtype
---  ------  -----
 0   CustId  object
 1   Rating  float64
dtypes: float64(1), object(1)
memory usage: 367.1+ MB

In [14]:
netflix_dataset.isnull().sum().sum()

np.int64(4499)

In [16]:
netflix_dataset.duplicated().sum()

np.int64(22234208)